### ISSUE TITLE
tweets are truncated

### ISSUE THREAD

**Issue by glyph** [python-twitter-tools/twitter#398]
When I run `twitter friends`, the tweets I get back are all truncated to 140 characters. I assume this is because something about the way the API is being accessed is outdated?  It would be great if this could be fixed.

**Comment by RouxRC** [comment]
Hi,
This is  a change in behavior of Twitter API since the change from 140 to 280 characters, extra options need to be passed to get what they call "extended" tweets.
Can you try and add into `twitter/cmdline.py` the following line after line 526 : 
```
                tweet_mode="extended",
```
Then retry it and it this fixes it let me knwo or propose a pull request?

**Comment by tephyr** [comment]
This is fixed in the master branch - I tested it with Python 3.8.1, and it showed the entire tweet text.  I installed it straight from git to test with `pip install git+git://github.com/sixohsix/twitter.git#twitter`.

**Comment by hugovk** [comment]
Time for a new release!

It's been over 2 years since https://github.com/sixohsix/twitter/releases/tag/twitter-1.18.0 came out.

@RouxRC Please could you make a new release?

**Comment by RouxRC** [comment]
I merged what I can, unfortunately, I don't believe I was granted pypi rights on the repo by @sixohsix 
Mike could you release a new version? Or could you give me the rights? (I'm boogheta on pypi)

**Comment by boogheta** [comment]
1.19 is finally released ! \o/
